name: habit_maker
description: A small but well-architected Flutter app to build habits with XP and a companion.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.1.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1
  lints: ^3.0.0

flutter:
  uses-material-design: true
